version: '{build}'
image: Visual Studio 2017
skip_tags: true
pull_requests:
  do_not_increment_build_number: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
     secure: Ggx6TlzRHUhBJzBlXHLQOepde26ODej0NODgNKlczHfB3/jqTZMf8Ro123i1pVPz
build_script:
  - dotnet build -c Release
test_script:
- ps: >-

    nuget install xunit.runner.console -OutputDirectory packages -Version 2.3.1
    
    nuget install OpenCover -OutputDirectory packages -Version 4.7.922

    dotnet tool install coveralls.net --version 1.0.0 --tool-path tools

    cd .\NetCasbin.UnitTest\bin\Release\netcoreapp2.0

    ..\..\..\..\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -target:dotnet.exe "-targetargs:""..\..\..\..\packages\xunit.runner.console.2.3.1\tools\netcoreapp2.0\xunit.console.dll"" "".\NetCasbin.UnitTest.dll"" -noshadow -appveyor" -filter:"+[NetCasbin]*  -[NetCasbin.UnitTest]*" -register:user -oldStyle -output:..\..\..\..\opencoverCoverage.xml
    
    cd ..\..\..\..\ 
    
    $coveralls = ".\tools\csmacnz.coveralls.exe"

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
