version: '{build}'
image: Visual Studio 2017
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: 7ZrzjrrwL6JAHiT8h5KsUbT4kXdLYLDtc
build_script:
  - dotnet build -c Release
test_script:
- ps: >-
    nuget install xunit.runner.console -OutputDirectory packages -Version 2.3.1
    
    nuget install OpenCover -OutputDirectory packages -Version 4.6.166

    dotnet tool install coveralls.net --version 1.0.0 --tool-path tools

    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:dotnet.exe "-targetargs:"".\packages\xunit.runner.console.2.3.1\tools\netcoreapp2.0\xunit.console.dll"" ""NetCasbin.UnitTest\bin\Release\netcoreapp2.1\NetCasbin.UnitTest.dll"" -noshadow -appveyor" -filter:"+[GameOfLife*]*" -oldStyle -output:opencoverCoverage.xml
    
    $coveralls = ".\tools\csmacnz.coveralls.exe"

    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
